alpha to RenderOp with automatic shader props
lightning-js/renderer pull request #18
Opened 2023-09-29 09:11 UTC by jfboeve

I've added alpha to the shader props which can be used for automatic shader props similar to [$dimensions](https://github.com/lightning-js/renderer/pull/1). This is a prop we need  for some of the DynamicShader effects.

This also pull request is related to #15

2023-09-29 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lightning-js/renderer?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lightning-js/renderer?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lightning-js/renderer?pullRequest=18) it.</sub>

2023-10-03 03:27 UTC, frank-weindel commented on src/core/renderers/webgl/shaders/DynamicShader.ts
> +  ): Record<string, unknown> {
Is this necessary?

2023-10-03 03:29 UTC, frank-weindel commented on src/core/renderers/webgl/WebGlCoreShader.ts
> +export interface AutomaticShaderProps {
There should be a new interface for the automatic alpha prop. You can have `DynamicShaderProps` implement multiple interfaces in order to pass both props (and all the documentation tied to them) up. This allows each shader to define specifically which automatic props it requires.

2023-10-03 03:30 UTC, frank-weindel commented on src/core/renderers/webgl/shaders/RoundedRectangle.ts
> +  ): Record<string, unknown> {
Same as above. Is there a reason for this? The point of having the return type be specific is so TypeScript can tell us if we don't fill out all the proper defaults.

2023-10-03 03:31 UTC, frank-weindel commented on src/core/renderers/webgl/shaders/RoundedRectangle.ts
> +  protected override bindProps(props: RoundedRectangleProps): void {
bindProps should always be getting the props after defaults were applied.

2023-10-03 03:31 UTC, frank-weindel requested changes
See comments

2023-10-03 08:25 UTC, jfboeve commented on src/core/renderers/webgl/WebGlCoreShader.ts
> +export interface AutomaticShaderProps {
Alright I've reverted that interface back to DimensionsShaderProp, and added AlphaShaderProp. This resolves the Record<string, unknown> and Required Issues mentioned in other comments too.

2023-10-03 11:35 UTC, frank-weindel approved these changes

2023-10-03 11:41 UTC, frank-weindel commented on src/core/renderers/webgl/WebGlCoreRenderer.ts
> +        alpha
@jfboeve missing a comma. This is causing a TS error

2023-10-03 11:42 UTC, frank-weindel requested changes
See comment. There's a TS error

2023-10-03 12:05 UTC, chiefcll commented on src/core/renderers/webgl/WebGlCoreRenderer.ts
> +        alpha
dangling commas - should the linter auto fix this?

2023-10-04 02:06 UTC, frank-weindel commented on src/core/renderers/webgl/WebGlCoreRenderer.ts
> +        alpha
Nah this was a legit syntax error

2023-10-04 13:55 UTC, jfboeve commented on src/core/renderers/webgl/WebGlCoreRenderer.ts
> +        alpha
Sorry must have gone wrong while merging, also alpha needed to be extracted from the curRenderOp.

2023-10-04 18:49 UTC, merged