Feat/render bounds
lightning-js/renderer pull request #191
Opened 2024-03-07 13:36 UTC by jfboeve

This pull request contains an implementation that excludes nodes that are located outside of the clippingrect/viewport from being added as quads. You can also add boundsMargin in order to extend the area in which nodes will still be loaded as quads

2024-03-07 21:02 UTC, wouterlucas commented
Squashed a bit of the commit log and fixed the test. @frank-weindel I'd imagine this would need an `INode` extension too to support `onOutOfViewport` / `onInViewport` too for my editor to stop complaining about it?

![image](https://github.com/lightning-js/renderer/assets/1534440/5b874817-3642-49af-9a09-82be674bd98e)

2024-03-08 16:01 UTC, frank-weindel commented
> Squashed a bit of the commit log and fixed the test. @frank-weindel I'd imagine this would need an `INode` extension too to support `onOutOfViewport` / `onInViewport` too for my editor to stop complaining about it?
> 
> ![image](https://private-user-images.githubusercontent.com/1534440/311035722-5b874817-3642-49af-9a09-82be674bd98e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTM5MjcsIm5iZiI6MTcwOTkxMzYyNywicGF0aCI6Ii8xNTM0NDQwLzMxMTAzNTcyMi01Yjg3NDgxNy0zNjQyLTQ5YWYtOWEwOS04MmJlNjc0YmQ5OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTYwMDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFjZmJhNjVkMTFiZWEwMWZmYTQ2MGE1NDI4NDI0ZjdkM2ExOWYyNGNhM2RlNDY1MDc2NjE3MTU3NmM2NTQ2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SqnhgSwXoSolg5odLYvIeoHZtlBSgrMP-Q0oaE6LaqI)

Yep. But furthermore we should use the event emitter for this. This is exactly the kind of thing it is designed for.

2024-03-08 16:06 UTC, jfboeve commented
So the reason I did this is because right now we are emitting emits... which I'm not sure if its the way to go ? With this solution you can just hook directly to the node and only add a listener when a user actually need one.

2024-03-08 16:10 UTC, frank-weindel commented on src/render-drivers/main/MainOnlyNode.ts
> +    this.coreNode.on('OutOfBounds', fn);
All events names should begin with a lower case letter to remain consistent with existing events: `outOfBounds`, `inBounds`, `outOfViewport`, `inViewport`

2024-03-08 16:38 UTC, frank-weindel commented on src/core/text-rendering/renderers/TextRenderer.ts
> +import type { RenderCoords } from '../../lib/RenderCoords.js';
Currently unused. Do you have a plan to use it?

2024-03-08 16:38 UTC, frank-weindel commented on src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
> +import type { RenderCoords } from '../../../lib/RenderCoords.js';
Currently unused. Do you have a plan to use it?

2024-03-08 19:58 UTC, frank-weindel requested changes
See comments

2024-03-11 09:50 UTC, jfboeve commented on src/render-drivers/main/MainOnlyNode.ts
> +    this.coreNode.on('OutOfBounds', fn);
changed the renderstate events to fall in line with the way Texture events are emitted.

2024-03-11 09:51 UTC, jfboeve commented on src/core/CoreNode.ts
> +      this.updateRenderState();
moved this call, to after the render coords are made.

2024-03-11 09:51 UTC, jfboeve commented on src/core/text-rendering/renderers/TextRenderer.ts
> +import type { RenderCoords } from '../../lib/RenderCoords.js';
cleaned up

2024-03-11 09:51 UTC, jfboeve commented on src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
> +import type { RenderCoords } from '../../../lib/RenderCoords.js';
cleaned up

2024-03-11 09:56 UTC, jfboeve commented on src/core/CoreNode.ts
> +      this.renderCoords = new RenderCoords([
Actually for the CoreNode / CoreRenderer I want to keep the `RenderCoords` for a different optimalisation. where we pass the `RenderCoords` to the CoreRenderer `addQuad` function. This would mean that we won't have to calculate the coords again which is happening now every time a node is added as quad.

However for this to properly work there are some changes needed in the TextCanvasRenderer which I plan to do in a different PR as it is unrelated to this feature.

2024-03-11 13:51 UTC, frank-weindel commented on src/core/CoreNode.ts
> +      this.renderCoords = new RenderCoords([
Gotcha. I think I see where you are going with it and it makes sense. I'd then just suggest some optimizations to maybe cut down on array allocations and maybe reusing a single RenderCoords instance, similar to how its done for matrices and some rect/bounds instances.

2024-03-11 14:55 UTC, frank-weindel commented
> So the reason I did this is because right now we are emitting emits... which I'm not sure if its the way to go ? With this solution you can just hook directly to the node and only add a listener when a user actually need one.

It is the way it is now. If we want to optimize that we need to look at it holistically. I personally rather not have a system that provides an EventEmitter AND specific event hook methods. It should be one or the other. EventEmitter provides lots of tools. It is possible we could improve the EventEmitter by not hooking up events that aren't being ultimately listened for.

2024-03-12 09:34 UTC, jfboeve commented on src/core/CoreNode.ts
> +      this.renderCoords = new RenderCoords([
I've updated the RenderCoords and some Bound instances!

2024-03-15 15:05 UTC, frank-weindel commented
This looks pretty good to me now! I just wish we had an automated way of testing it. It might be possible in a visual regression test using text to verify that the appropriate events fire when moving a node in and out of the render bounds/viewport.

2024-03-18 10:36 UTC, wouterlucas approved these changes
LGTM!

2024-03-18 10:38 UTC, wouterlucas commented
> This looks pretty good to me now! I just wish we had an automated way of testing it. It might be possible in a visual regression test using text to verify that the appropriate events fire when moving a node in and out of the render bounds/viewport. Curious if you have any thoughts on it.

could probably do a vitetest unit test around it without actually rendering something? Stub the addQuads part and run some dummy coordinates/positions? Thought not a quick thing to set up.

2024-03-18 20:45 UTC, frank-weindel commented
> could probably do a vitetest unit test around it without actually rendering something? Stub the addQuads part and run some dummy coordinates/positions? Thought not a quick thing to set up.

Right, not quick to set up. I figured with a VRT test you're testing the whole pipeline.

2024-03-19 12:23 UTC, frank-weindel approved these changes

2024-03-19 13:34 UTC, merged