Feature: texture factory
lightning-js/renderer pull request #256
Opened 2024-04-23 07:17 UTC by elsassph

Introduce a "texture factory" pattern, allowing applications to provide cacheable custom textures.

Changes to `ImageTexture`:
- Open `src` to allow a `() => ImageData`,
- Add `key` prop allowing to cache `ImageData` based textures.

```
function getTexture(): ImageData {...}
const textureKey = 'custom-texture-x-y-z';

renderer.createTexture("ImageTexture", {
  src: getTexture,
  key: textureKey,
});
```

TODO: I would like to add a case in `examples/tests`

2024-04-23 13:39 UTC, frank-weindel commented
Looks good to me! What particular use case did you implement this for?

2024-05-19 18:32 UTC, elsassph commented
Completed!

2024-05-27 18:17 UTC, wouterlucas requested changes

2024-05-27 18:17 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +    const key = resolvedProps.key ?? resolvedProps.src;
You have to be a bit careful with nullish coalescing operators in Typescript, they transpile quite some large vanilla JS (adding up to the bundle size) and doing 4 checks where a simple `||` would also work performs a lot better.

2024-05-27 18:17 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +    return `ImageTexture,${key},${resolvedProps.premultiplyAlpha ?? 'true'}`;
same here

2024-05-28 09:04 UTC, elsassph commented on src/core/textures/ImageTexture.ts
> +    const key = resolvedProps.key ?? resolvedProps.src;
I'm well familiar with how this transpiles, but it's fair to use `||` here.

2024-05-28 09:05 UTC, elsassph commented on src/core/textures/ImageTexture.ts
> +    return `ImageTexture,${key},${resolvedProps.premultiplyAlpha ?? 'true'}`;
That would be wrong here: `false` would be replaced by `true`

2024-05-28 09:09 UTC, elsassph commented on src/core/textures/ImageTexture.ts
> +      if (src instanceof ImageData) {
From a branching perspective, `string` is probably the most common case, so I thought it would be better to start narrowing on it. Then if it's not an `ImageData` it will be a function by elimination.

2024-05-28 09:14 UTC, elsassph commented on src/core/textures/ImageTexture.ts
> +    return `ImageTexture,${key},${resolvedProps.premultiplyAlpha ?? 'true'}`;
I added `?? 'true'` to fix the lint error `@typescript-eslint/restrict-template-expressions` because the value can be `null`

2024-05-29 05:47 UTC, elsassph commented on examples/tests/texture-factory.ts
> +export default async function ({
I can give it a try, but I suppose I can't use `Math.random()` in this case?

2024-05-29 05:50 UTC, elsassph commented on examples/tests/texture-factory.ts
> +export default async function ({
You have a lot of tests without automation where snapshot testing would be more relevant than here.

2024-05-29 12:46 UTC, frank-weindel commented on examples/tests/texture-factory.ts
> +export default async function ({
I didn't say there weren't. Just trying to push the needle on new features getting tests added to VRT. This seemed like an easy add.

2024-05-29 15:01 UTC, frank-weindel commented on examples/tests/texture-factory.ts
> +export default async function ({
We don't have a plan but I'll do one better and provide a PR:
- #282

2024-05-30 13:37 UTC, elsassph commented on examples/tests/texture-factory.ts
> +export default async function ({
Thanks, I added the `automation` function and it works for me when running local VRT.

I hope you don't want me to install Docker and build a DockerFile to create a CI screenshot. That's a line I don't want to cross haha.

2024-05-31 05:18 UTC, frank-weindel commented
Added the snapshot

2024-05-31 05:20 UTC, frank-weindel approved these changes

2024-05-31 05:22 UTC, merged