Ability to prevent a node from being GC'ed #349
lightning-js/renderer pull request #356
Opened 2024-08-13 08:29 UTC by Drulokia

2024-08-13 15:45 UTC, wouterlucas requested changes

2024-08-13 15:45 UTC, wouterlucas commented on src/core/TextureMemoryManager.ts
> +      if (!texture.preventCleanup) {
`texture.preventCleanup === false` will perform slightly better over a fallsy check, since we know its always going to be a boolean, might as well.

2024-08-13 17:54 UTC, elsassph commented on src/core/TextureMemoryManager.ts
> +      if (!texture.preventCleanup) {
Hard to believe, and I'm 99% sure that minification process will remove this "optimisation".

2024-08-15 11:20 UTC, chiefcll commented
Are there details on use case for this? Or some docs to reference? Is this primarily for Images rather than simply nodes?

2024-08-16 13:19 UTC, wouterlucas commented
> Are there details on use case for this? Or some docs to reference? Is this primarily for Images rather than simply nodes?

Exactly that, to prevent textures on a node from being cleaned up even when the memory threshold has been exceeded and/or they are out of the view port. It helps when you have nodes with textures that you know you're going to need nearly immediate;y regardless of whether it is in view port or not.

2024-08-16 13:20 UTC, wouterlucas approved these changes
LGTM

2024-08-21 19:14 UTC, merged