perf: Replace forEach with for loops
lightning-js/renderer pull request #383
Opened 2024-09-16 02:22 UTC by chiefcll

Hopefully reduces a bit of garbage collection. Only removing forEach on most used areas of the code. Also updated eslint to disable the no null assertion so typescript doesn't complain about undefined children.

2024-09-16 07:13 UTC, wouterlucas requested changes

2024-09-16 07:13 UTC, wouterlucas commented on src/core/CoreNode.ts
> +      for (let i = 0, length = this.children.length; i < length; i++) {
is there a reason to do an `length = this.children.length` over `i < this.children.length`?
Wouldn't `length` also need a `let` or `const` declaration?

If this is the same as taking `const length = this.children.length` prior to the for loop, which I believe Jeffrey has done on a couple of places before. I remember there was no measurable different between the two patterns.

2024-09-16 07:13 UTC, wouterlucas commented on src/core/CoreNode.ts
> +        this.children[i]!.setUpdateType(UpdateType.All);
You have to be careful with the TS `!` postfix, it does two things: checks for `undefined` and `null` whereas you can get away with just a `undefined` check here. Plus it gets transpiled to exactly that anyway.

2024-09-16 07:13 UTC, wouterlucas commented on .eslintrc.cjs
> +    '@typescript-eslint/no-non-null-assertion': 'off',
I don't think we'd want to turn this off - a warning would be fine.

2024-09-16 11:49 UTC, chiefcll commented on src/core/CoreNode.ts
> +        this.children[i]!.setUpdateType(UpdateType.All);
The ! tells typescript to ignore the possible error of an undefined coming back from the array due to accessing out of index - https://www.executeprogram.com/courses/typescript-basics/lessons/undefined-in-arrays#:~:text=There's%20a%20case%20where%20TypeScript,case%2C%20TypeScript%20will%20return%20undefined%20.

Doing a `if (this.children !== undefined)` is an extra check and doesn't get compiled away.

2024-09-16 11:51 UTC, chiefcll commented on src/core/CoreNode.ts
> +      for (let i = 0, length = this.children.length; i < length; i++) {
I'm kinda surprised as you'd be checking the length of the array each time during the loop. It should be faster to store the length as the array length could change and must be rechecked each loop.

https://stackoverflow.com/questions/8452317/do-loops-check-the-array-length-every-time-when-comparing-i-against-array-length

2024-09-20 12:40 UTC, wouterlucas commented on src/core/CoreNode.ts
> +      for (let i = 0, length = this.children.length; i < length; i++) {
yeah that used to be an issue - seems to be less a problem with newer webkits/chromium last time we spend a morning playing with WPEWebKit and different chromium versions in . Eitherway its all very marginal and doesn't hurt to keep it that way.

2024-09-20 12:41 UTC, wouterlucas approved these changes
LGTM

2024-09-20 12:54 UTC, merged