compat: Remove fromEntries for older browser support
lightning-js/renderer pull request #385
Opened 2024-09-17 14:25 UTC by chiefcll

Functionally the same thing - fromEntries requires Chrome 73. This will allow renderer to work on older devices a bit easier without vite needing to transpile it away.

2024-09-17 15:08 UTC, elsassph commented on src/core/text-rendering/renderers/TextRenderer.ts
>      this.set = Object.freeze(
While we look at that: `Object.freeze` is notoriously slow in older browsers.

2024-09-20 12:38 UTC, wouterlucas requested changes

2024-09-20 12:38 UTC, wouterlucas commented on src/core/text-rendering/renderers/TextRenderer.ts
> +    );
why not avoid entries and reduce all together with a simple for loop?
Entries would still be polyfilled anyway since its Chrome 54 I believe? Save some more and go all the way.

Something like:
```js
const propSettersMap: TrPropSetters<StateT> = {};

const keys = Object.keys(propSetters);
for (let i = 0; i < keys.length; i++) {
  const key = keys[i] as keyof TrProps;
  const setter = propSetters[key];

  propSettersMap[key] = (state: StateT, value: TrProps[key]) => {
    if (state.props[key] !== value) {
      setter(state, value as never);
      this.stage.requestRender();
    }
  };
}
```

should do it?

2024-09-20 12:38 UTC, wouterlucas commented on src/core/text-rendering/renderers/TextRenderer.ts
>      this.set = Object.freeze(
Agree - though you can't get similar immutability that freeze gives you. Object.assign comes close enough for the usecase.

Something like:
```js
this.set = {};
Object.keys(propSetters).forEach(key => {
  Object.defineProperty(this.set, key, {
    value: propSetters[key],
    writable: false,  // Prevents property from being changed
    configurable: false  // Prevents property from being deleted
  });
});
```

And replace that with the `propSetterMap` and we should be good to go?

2024-09-25 14:42 UTC, wouterlucas approved these changes
LGTM

2024-09-25 14:47 UTC, merged