fix: loadImage on a device without creteImageBitmap
lightning-js/renderer pull request #410
Opened 2024-10-08 15:03 UTC by pecoram

This PR addresses an issue specific to 2017 Samsung TVs, which do not support the createImageBitmap method. 
Additionally, I implemented a fallback for cases where createImageBitmap is supported but the fetch operation fails (for example when using a polyfill), ensuring compatibility across different scenarios.

Testing
- Tested on 2017 Samsung TVs.

2024-10-08 15:14 UTC, elsassph commented on src/core/textures/ImageTexture.ts
> +        const base64data = base64DataFromSrc(src);
This looks very unsafe:

- There can be many errors caught here,
- It seems to be blindly trying to parse `src` as a data URL, while this seem like a very specific case.

2024-10-08 16:18 UTC, pecoram commented on src/core/textures/ImageTexture.ts
> +        const base64data = base64DataFromSrc(src);
like this is better?

2024-10-09 08:37 UTC, wouterlucas requested changes
Honestly I don't think we should do fallback when we can predetermine that the `createImageBitmap` won't work.

In such case we should just rely on `Image()` and turn off the path that involves `createImageBitmap`.

2024-10-09 08:37 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +      try {
if `fetch` is a promise, why wrap it in a try/catch block?

2024-10-09 08:37 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +        if (src.startsWith('data:')) {
wouldn't it make more sense to do the `src.startsWith('data:')` check up top before or just after we do `fetch`? Sounds expensive to always make the fetch fail first, deal with the error chain and then try to parse a `data` blob. 

If its only an error case you're worried about, why not: 
```ts
const response = await fetch(src).catch( e => { /* .... handle error */ });

if (!response && src.startWith('data:')) {
  /* ... do alternate parsing here */
}
```

If this if this is a 1 in 10 or 1 in 100 time case, going through the try/catch error chain to then figure out its a `data:` and do an alternative path is very expensive.

2024-10-09 08:37 UTC, wouterlucas commented on src/core/lib/utils.ts
> +  base64Content = base64Content ?? src;
if it didn't match, it would still return src and then fail down below in the base64toBlob?
I think we should handle the error case more strictly if we can figure it is not Base64 and bail out gracefully.

2024-10-09 08:37 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +        if (src.startsWith('data:')) {
I honestly think this is a bad idea, rather keep things straight and neat instead of trying to fallback and make it work. If the feature is not available, we shouldn't try to make it work. It will cause confusion.

2024-10-09 10:43 UTC, pecoram commented on src/core/textures/ImageTexture.ts
> +        if (src.startsWith('data:')) {
What can I do is using a function like this:

```
async function supportsDataURLFetch() {
  try {
    await fetch('data:text/plain,Test');
    return true;
  } catch (error) {
    return false;
  }
}
```

and check it at startup

2024-10-09 11:20 UTC, elsassph commented on src/core/textures/ImageTexture.ts
> +      try {
It's idiomatic nowadays to `try { await } catch`

2024-10-09 11:31 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +      try {
is it? that doesn't automatically mean its a good idea 🙃

2024-10-09 11:43 UTC, wouterlucas commented on src/core/textures/ImageTexture.ts
> +        if (src.startsWith('data:')) {
two questions:
* Does polyfilling it actually helps over just turning createImageBitmap support off?
* What polyfill are you using, as this seems like limitations of the polyfill?

2024-10-09 12:29 UTC, pecoram commented on src/core/textures/ImageTexture.ts
> +        if (src.startsWith('data:')) {
I used the polyfill (https://gist.github.com/pseudosavant/a6d970b945ae85ef4dbc43200da94faf) because the images were not taking the correct size, but with polyfill it was giving me that exception. Then I realised that by removing width and height from the new Image everything worked correctly and then I removed the polyfill. I added the fallback in the PR to avoid possible problems like this.

2024-10-14 07:35 UTC, pecoram commented
OK - I'm opening the PR with just the change we need, then we'll consider whether to go ahead with this

2025-01-27 14:24 UTC, closed without merging