428 dynamic bounds margin
lightning-js/renderer pull request #467
Opened 2024-12-10 09:59 UTC by Drulokia

Added option to set boundsmargin on node level.
Also able to change it after creation.

2024-12-11 14:49 UTC, jfboeve requested changes
Hey I went through the code the initial work looks good, however I've found some points I would like to see added / changed:

For the Stage.ts:
- Set the default boundsMargin of the stage when creating the rootNode.
- Add getter/setter for boundsMargin on Stage and have it also adjust the boundsMargin of the rootNode.

For the CoreNode:
- for `get boundsMargin` I don't think we need to check if the boundsMargin in the props is an Array or not, just check if this.props.boundsMargin is not null and return that value. If it is null let it check the parent node(s) with the changes to Stage we won't need the stage.boundsMargin
- In case the boundsMargin for a CoreNode is set upon creating the node we should call the boundsMargin setter like we are doing with the shaders/texture (line: 761)

2024-12-12 20:48 UTC, wouterlucas approved these changes
LGTM

2025-01-06 16:52 UTC, Drulokia commented
Added dynamic boundsmargin option to stage, also boundsmargin can be set to null, so it can take over parents boundsmargin or stages boundsmargin.

Went throught the changes requested by @jfboeve

2025-01-08 10:15 UTC, jfboeve commented
I agree with you @wouterlucas since the renderBounds are calculated based on boundsMargin it's better to add it to the RenderBound

2025-01-08 13:04 UTC, Drulokia commented
I had it seperate because the renderBounds did only propagate 1 child up.
I checked if it had impact if it did all children and it doesn't.
Changed it to be handled in renderBounds UpdateType

2025-01-09 16:05 UTC, wouterlucas requested changes

2025-01-13 10:59 UTC, wouterlucas approved these changes
Thanks!

2025-01-17 14:14 UTC, jfboeve approved these changes

2025-01-17 15:20 UTC, wouterlucas commented
can you rebase it @Drulokia ?

2025-01-22 20:32 UTC, wouterlucas commented
I think you had a merge issue with the unit tests, seems broken after the rebase/merge with main:
https://github.com/lightning-js/renderer/actions/runs/12904794534/job/35982692173?pr=467#step:8:30

2025-02-21 12:37 UTC, merged