feat: Add width / height to ImageTexture
lightning-js/renderer pull request #68
Opened 2023-10-26 20:35 UTC by pecoram

should to fix https://github.com/lightning-js/renderer/issues/34

2023-10-27 17:25 UTC, frank-weindel requested changes
Thanks for the PR @pecoram! Please discuss with us in #34. I'm not a fan of tying this directly to 0 values and we do need to consider Text in how this functions.

2023-10-31 15:00 UTC, frank-weindel commented
Labeling this as a breaking change as it's possible downstream frameworks/apps will behave differently without changes when this feature is implemented.

2023-10-31 16:23 UTC, frank-weindel commented on src/core/CoreNode.ts
> +        (this.width === 0 && this.height === 0)
We shouldn't try to handle aspect ratios. If the `autosize` property is true, it should just set the width/height to the width and height of the texture.

2023-10-31 16:29 UTC, frank-weindel commented on src/core/CoreNode.ts
> +    if (target.props.src) {
Keep in mind that the `src` property does not exist at all in the Core API Space. It's implementation only exists in the Main API Space, split between MainOnlyNode.ts and ThreadXMainOnlyNode.ts.

https://github.com/lightning-js/renderer/blob/6e9dc53d0dd58a7c949e31d5d4db0770e8b01f5e/src/render-drivers/main/MainOnlyNode.ts#L347C12-L363

https://github.com/lightning-js/renderer/blob/6e9dc53d0dd58a7c949e31d5d4db0770e8b01f5e/src/render-drivers/threadx/ThreadXMainNode.ts#L109-L125

2023-11-03 21:22 UTC, chiefcll reviewed
👍

2023-11-06 16:51 UTC, frank-weindel commented on src/main-api/INode.ts
> +   * @default `null`
I think this is unintended

2023-11-06 16:53 UTC, frank-weindel commented on src/main-api/INode.ts
> +  autosize: boolean | null;
`null` will not work as a value on the ThreadX implementation. For now, just make setting `src` (in both MainOnlyNode and ThreadXMainNode) also set `autosize` to true unconditionally

2023-11-06 16:53 UTC, frank-weindel commented on src/main-api/INode.ts
> +  autosize: boolean | null;
`null` will not work as a value on the ThreadX implementation. For now, just make setting `src` (in both MainOnlyNode and ThreadXMainNode) also set `autosize` to true unconditionally

2023-11-06 16:54 UTC, frank-weindel commented on src/core/CoreNode.ts
>      if (this.autosize && dimensions.width && dimensions.height) {
I don't think we need to condition this on width/height being truthy. If the dimensions are truly somehow 0x0 then autosizing should still occur

2023-11-08 15:00 UTC, frank-weindel commented on src/main-api/INode.ts
> +  autosize: boolean | null;
I understand what you're trying to do here. But at the moment there's a limitation in how that can be done. For now we'll need to rely on the order of setting the properties to allow the user to set `autosize` to false if they also set `src`. This is something we can improve on in the future.

2024-04-04 15:00 UTC, merged